import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider";
import Link from "next/link";
import Navbar from "@/components/navbar";
import Menu from "@/components/menu";
import { NextAuthSessionProvider } from "@/components/session-provider";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${inter.className} dark`}>
        <NextAuthSessionProvider session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            <div className="hidden lg:block fixed h-full top-[50px] border-r p-2.5 w-full max-w-[100px]">
              <Menu />
            </div>
            <div className="lg:ml-[100px] mt-[55px] lg:mt-[50px] px-5 py-2.5  lg:p-2.5  ">
              {children}
            </div>
          </ThemeProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
