import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Menu from "@/components/menu";
import Navbar from "@/components/navbar";
import { NextAuthSessionProvider } from "@/components/session-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { getServerSession } from "next-auth";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden `}>
        <NextTopLoader />
        <NextAuthSessionProvider session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            <div className="hidden lg:block fixed h-full top-[55px] border-r p-2.5 w-full max-w-[100px]">
              <Menu />
            </div>
            <div className="lg:ml-[100px] mt-[55px]  px-5 py-2.5  lg:p-2.5 ">
              {children}
            </div>
            <Toaster />
          </ThemeProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
