import ClientProviders from "@/components/client-providers";
import Menu from "@/components/menu";
import Navbar from "@/components/navbar";
import { NextAuthSessionProvider } from "@/components/session-provider";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden `}>
        <NextAuthSessionProvider session={session}>
          <ClientProviders>
            <Navbar />
            <div className="hidden lg:block fixed h-full top-[55px] border-r p-2.5 w-full max-w-[100px]">
              <Menu />
            </div>
            <div className="lg:ml-[100px] mt-[55px]  px-5 py-2.5  lg:p-2.5 ">
              {children}
            </div>
          </ClientProviders>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
